### ISSUE TITLE
As a user, I want to be notified when entering an incorrect private code and the game shouldn't start, in order to get feedback and play the set I want

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizz.me#116]
### Criteria

- [ ] give visual feedback when entered private code is incorrect/unknown
- [ ] prevent game from starting anyway

### To-Dos

- [ ] verify entered private code with codes in db
- [ ] only if match with questions is found, start the game
