### ISSUE TITLE
As a user, I want to get feedback to my answers

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizz.me#17]
### Criteria

- [x] let the user know if he answered rightly or wrongly
- [x] directly after each question
- [x] give visual feedback 
- [x] show correct answer

### To-Dos

- [ ] 
- [ ]
- [ ]
