### ISSUE TITLE
As a developer, I want to add a check, when choosing a new private code , in order to prevent mix-ups with other private sets or public questions

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizz.me#64]
### Criteria

- [ ] choosen private code (hash) must be unique
- [ ] to verify this, all categories and codes from the db have to be checked
- [ ]

### To-Dos

- [ ] get all categories (and codes) of  old questions from db
- [ ] check if 'new code' doesn't match existing ones
- [ ] if matches, throw error, to make user change it and don't link further before code is unqiue
