### ISSUE TITLE
As a developer, I want to allow the user to A) choose categories  or B) to look for a set with a code, but not both to prevent bugs 

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizz.me#68]
### Criteria

- [ ] allow the one or the other but not both
- [ ] prevent changing the other one when first one is allready altered
- [ ] return error if both want to be changed

### To-Dos

- [ ] check for content and block other  input (no error message necessary)
- [ ] OR check if both have content and then return error
- [ ]
