### ISSUE TITLE
As a user, I want to switch through themes, in order to adjust the design

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizz.me#77]
### Criteria

- [ ] change theme by clicking the color palette
- [ ]  have at least 3 themes
- [ ]

### To-Dos

- [ ] find and implement color schemes in themes
- [ ] functionality of color palette button in header
- [ ]
